### ISSUE TITLE
getTableNameByClassName

### ISSUE THREAD

**Issue by dxwy2001** [swoft-cloud/swoft-db#20]
QueryBuilder类的getTableNameByClassName 当tableName 为mysql保留字或者关键字的时候会报异常

**Comment by huangzhhui** [comment]
异常信息麻烦提供一下

**Comment by dxwy2001** [comment]
调用方式是这样的Release::findById(1)->getResult();
异常是Mysql recv error，connectError= error=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'release WHERE  `id` = '1' LIMIT 0,1' at line 1
