### ISSUE TITLE
关于数据库操作中每次获取结果都需要 getResult()

### ISSUE THREAD

**Issue by Hiber0385** [swoft-cloud/swoft-db#27]
一直在不明白 为何 所有的数据库获取结果操作如get(),save(),insert()等等都需要加上getResult() 来获取结果,为何不产生上述操作的时候直接自动getResult() 呢

**Comment by huangzhhui** [comment]
@Hiber0385 这个是并发查询的操作，可以参考https://wiki.swoole.com/wiki/page/604.html
